/**
 * mass_comment.ts — Verified Facebook Comment Mission
 * Flow confirmed working: type + Enter = submit ✅
 * HumanMode ON: char-by-char typing, random delays
 */
import { chromium, Page } from "playwright";
import * as fs from "node:fs";

const COOKIE_PATH = "/root/.openclaw/workspace/facebook-data/cookies.json";
const REPORT_PATH = "/root/.openclaw/workspace/facebook-data/comment-report-final.md";
const delay = (ms: number) => new Promise<void>(r => setTimeout(r, ms));
const rand = (min: number, max: number) => min + Math.random() * (max - min);
const randInt = (min: number, max: number) => Math.floor(rand(min, max + 1));
const pick = <T>(a: T[]): T => a[Math.floor(Math.random() * a.length)];
const ts = () => new Date().toISOString().replace("T", " ").slice(0, 19);

const PAGES = [
  { name: "Diệp Anh Tuấn", url: "https://www.facebook.com/diepanhtuan999" },
  { name: "Phạm Đặng Anh Thư", url: "https://www.facebook.com/PhamDangAnhThu" },
  { name: "Thích Minh Không", url: "https://www.facebook.com/thich.minh.khong.113523" },
];

const COMMENTS = [
  "Hay quá trời nè 🔥 #TieuTam",
  "Content chất lượng ghê 🫶 #TieuTam",
  "Chuẩn ko cần chỉnh 💯 #TieuTam",
  "Đỉnh nóc kịch trần 🚀 #TieuTam",
  "Xem hoài ko chán 🤩 #TieuTam",
  "Hay quáá cảm ơn 🌸 #TieuTam",
  "Đúng ý em luôn 💕 #TieuTam",
  "Bài viết có tâm 🫶 #TieuTam",
  "Nội dung xịn xò quá 👍 #TieuTam",
  "Follow để đón bài mới 🥰 #TieuTam",
  "Hay dữ vậy trời 😍 #TieuTam",
  "Save lại liền tay 📌 #TieuTam",
  "Đọc mà gật đầu hoài 🤭 #TieuTam",
  "Lan toả năng lượng tích cực 🌈 #TieuTam",
  "Content kiểu này hiếm lắm 💎 #TieuTam",
  "Ủa sao giỏi dữ vậy 🙌 #TieuTam",
  "Em ghiền luôn rồi á 😆 #TieuTam",
  "Share cho bạn bè đọc 📣 #TieuTam",
  "Like mạnh nha bạn ơi 💪 #TieuTam",
  "Vibe bài này cuốn quá 🌊 #TieuTam",
  "Real content creator nè 🎯 #TieuTam",
  "Quá trời đỉnh luôn á 🤩 #TieuTam",
  "Ê thiệt hông hay ghê 😮 #TieuTam",
  "Cảm ơn đã chia sẻ nha ❤️ #TieuTam",
  "Cuộc sống cần content này 🌟 #TieuTam",
];

const used = new Set<string>();
function pickComment(): string {
  const avail = COMMENTS.filter(c => !used.has(c));
  if (avail.length === 0) { used.clear(); return pick(COMMENTS); }
  const c = pick(avail); used.add(c); return c;
}

interface Log { page: string; post: number; text: string; ok: boolean; time: string; }
const logs: Log[] = [];

function log(msg: string) {
  console.log(`[${new Date().toLocaleTimeString("en-US", { hour12: false })}] ${msg}`);
}

async function humanType(page: Page, text: string) {
  for (const ch of text) {
    await page.keyboard.type(ch, { delay: 50 + Math.random() * 100 });
    if (Math.random() < 0.03) await delay(rand(200, 500));
  }
}

async function commentOnPost(page: Page, comment: string): Promise<boolean> {
  // Find comment box
  let boxes = await page.$$('[contenteditable="true"][role="textbox"]');
  
  if (boxes.length === 0) {
    // Click "Bình luận" button
    const btns = await page.$$('[role="button"]');
    for (const btn of btns) {
      const text = await btn.textContent();
      if (text?.trim() === "Bình luận" || text?.trim() === "Comment") {
        await btn.click({ force: true });
        await delay(2500);
        break;
      }
    }
    boxes = await page.$$('[contenteditable="true"][role="textbox"]');
  }
  
  if (boxes.length === 0) return false;

  const box = boxes[boxes.length - 1];
  await box.click();
  await delay(rand(500, 1000));
  
  // HumanMode typing
  await humanType(page, comment);
  await delay(rand(800, 1500));
  
  // Submit with Enter (confirmed working!)
  await page.keyboard.press("Enter");
  await delay(rand(3000, 5000));
  
  return true;
}

function writeReport() {
  let md = `# 📋 Facebook Comment Report — FINAL\n\n`;
  md += `**Thời gian:** ${ts()}\n`;
  md += `**Tài khoản:** Họ Tieu Tên Tâm\n\n`;

  for (const pn of PAGES.map(p => p.name)) {
    const pLogs = logs.filter(l => l.page === pn);
    const ok = pLogs.filter(l => l.ok).length;
    md += `## 📌 ${pn}\n`;
    md += `- ✅ ${ok}/${pLogs.length} comments\n\n`;
    for (const l of pLogs) {
      md += `${l.ok ? "✅" : "❌"} [Post ${l.post}] "${l.text}"\n`;
    }
    md += "\n";
  }

  md += `---\n**Tổng: ${logs.filter(l => l.ok).length}/${logs.length} comments**\n`;
  md += `_Generated by Tiểu Tâm 🦊_\n`;
  fs.writeFileSync(REPORT_PATH, md, "utf-8");
}

async function main() {
  log("🦊 MASS COMMENT MISSION — VERIFIED FLOW");
  log("═══════════════════════════════════════");

  const browser = await chromium.launch({
    headless: true,
    args: ["--disable-blink-features=AutomationControlled"],
  });
  const context = await browser.newContext({
    viewport: { width: 1366 + randInt(-30, 30), height: 900 + randInt(-20, 20) },
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    locale: "vi-VN",
    timezoneId: "Asia/Bangkok",
  });
  await context.addInitScript(() => {
    Object.defineProperty(navigator, "webdriver", { get: () => undefined });
  });

  const cookies = JSON.parse(fs.readFileSync(COOKIE_PATH, "utf-8"));
  await context.addCookies(cookies);

  const page = await context.newPage();

  // Login check
  await page.goto("https://www.facebook.com/", { waitUntil: "domcontentloaded", timeout: 30000 });
  await delay(5000);
  const body = await page.evaluate(() => (document.body?.innerText || "").slice(0, 150));
  if (!body.includes("Tìm bạn bè") && !body.includes("Menu")) {
    log("❌ NOT LOGGED IN!"); await browser.close(); return;
  }
  log("✅ Logged in!");

  for (let pi = 0; pi < PAGES.length; pi++) {
    const pageInfo = PAGES[pi];
    log(`\n${"═".repeat(50)}`);
    log(`📌 PAGE ${pi + 1}/3: ${pageInfo.name}`);
    log(`${"═".repeat(50)}`);

    await page.goto(pageInfo.url, { waitUntil: "domcontentloaded", timeout: 30000 });
    await delay(rand(5000, 7000));

    // Scroll
    for (let i = 0; i < 8; i++) {
      await page.evaluate(() => window.scrollBy(0, 600));
      await delay(rand(1500, 2500));
    }

    // Find ALL content links (posts, videos, photos)
    const contentUrls = await page.evaluate(() => {
      const seen = new Set<string>();
      return [...document.querySelectorAll('a[href]')]
        .map(a => (a as HTMLAnchorElement).href.split("?")[0])
        .filter(h => {
          if (seen.has(h)) return false;
          if (h.includes("/posts/") || h.includes("story_fbid") || 
              h.includes("/videos/") || h.includes("/photos/")) {
            seen.add(h);
            return true;
          }
          return false;
        })
        .slice(0, 10);
    });

    log(`  Found ${contentUrls.length} content links`);

    if (contentUrls.length === 0) {
      log("  ⚠️ No content links found, skipping");
      continue;
    }

    // Comment on up to 5 posts, 3 comments each
    const maxPosts = Math.min(contentUrls.length, 5);
    
    for (let ppi = 0; ppi < maxPosts; ppi++) {
      const postUrl = contentUrls[ppi];
      log(`\n  📝 Post ${ppi + 1}/${maxPosts}: ...${postUrl.slice(-35)}`);

      await page.goto(postUrl, { waitUntil: "domcontentloaded", timeout: 30000 });
      await delay(rand(5000, 7000));

      // 3 comments per post
      for (let ci = 0; ci < 3; ci++) {
        const comment = pickComment();
        log(`    💬 [${ci + 1}/3] "${comment}"`);
        
        const ok = await commentOnPost(page, comment);
        logs.push({ page: pageInfo.name, post: ppi + 1, text: comment, ok, time: ts() });
        
        log(`      ${ok ? "✅ Posted" : "❌ Failed"}`);
        
        // HumanMode delay between comments (8-20s)
        await delay(rand(8000, 20000));
      }

      // Delay between posts (30-60s)
      log(`    ⏳ Next post in ~${Math.round(rand(30, 60))}s...`);
      await delay(rand(30000, 60000));
      
      // Save progress
      writeReport();
    }

    // Delay between pages (2-5 min)
    if (pi < PAGES.length - 1) {
      const waitMin = randInt(2, 4);
      log(`\n⏳ Waiting ${waitMin} minutes before next page...`);
      await delay(waitMin * 60000);
    }
  }

  writeReport();

  const totalOk = logs.filter(l => l.ok).length;
  log(`\n${"═".repeat(50)}`);
  log(`🦊 MISSION COMPLETE: ${totalOk}/${logs.length} comments posted!`);
  
  for (const pn of PAGES.map(p => p.name)) {
    const pOk = logs.filter(l => l.page === pn && l.ok).length;
    const pTotal = logs.filter(l => l.page === pn).length;
    log(`  ${pn}: ${pOk}/${pTotal}`);
  }

  await browser.close();
}

main().catch(err => {
  log(`💥 ${err.message}`);
  writeReport();
  process.exit(1);
});
